"""Add Schwab support to trading models

Revision ID: 5fe76bf46802
Revises: aaf944172360
Create Date: 2026-02-01 17:21:55.123088

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5fe76bf46802'
down_revision = 'aaf944172360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    trading_account_type = sa.Enum('IBKR', 'SCHWAB', name='tradingaccounttype')
    trading_account_type.create(op.get_bind(), checkfirst=True)

    op.add_column('trading_account_config', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='My Trading Account'))
    op.add_column('trading_account_config', sa.Column('account_type', trading_account_type, nullable=False, server_default='IBKR'))
    op.add_column('trading_account_config', sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trading_account_config', sa.Column('app_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trading_account_config', sa.Column('account_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trading_account_config', sa.Column('tokens_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('trading_account_config', 'host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trading_account_config', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trading_account_config', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('trading_account_summary', sa.Column('account_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trading_account_summary', 'trading_account_config', ['account_config_id'], ['id'])
    op.add_column('trading_positions', sa.Column('account_config_id', sa.Integer(), nullable=True))
    op.alter_column('trading_positions', 'con_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'trading_positions', 'trading_account_config', ['account_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trading_positions', type_='foreignkey')
    op.alter_column('trading_positions', 'con_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trading_positions', 'account_config_id')
    op.drop_constraint(None, 'trading_account_summary', type_='foreignkey')
    op.drop_column('trading_account_summary', 'account_config_id')
    op.alter_column('trading_account_config', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trading_account_config', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trading_account_config', 'host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trading_account_config', 'tokens_path')
    op.drop_column('trading_account_config', 'account_hash')
    op.drop_column('trading_account_config', 'app_secret')
    op.drop_column('trading_account_config', 'app_key')
    op.drop_column('trading_account_config', 'account_type')
    op.drop_column('trading_account_config', 'name')
    # ### end Alembic commands ###