"""add finance snapshots table

Revision ID: 6093b5cc0229
Revises: 3d7ac526bd6a
Create Date: 2026-01-22 21:07:15.392815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6093b5cc0229'
down_revision = '3d7ac526bd6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('total_liabilities', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_snapshots')
    # ### end Alembic commands ###