"""Add dividend positions table retry

Revision ID: 710cafd9a8c6
Revises: b75e2a944c8b
Create Date: 2026-01-31 19:26:09.054878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '710cafd9a8c6'
down_revision = 'b75e2a944c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_positions_account'), 'dividend_positions', ['account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_positions_account'), table_name='dividend_positions')
    op.drop_table('dividend_positions')
    # ### end Alembic commands ###