"""Add Execution table

Revision ID: 8250ff809a39
Revises: 
Create Date: 2025-07-02 23:44:10.878300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8250ff809a39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution',
    sa.Column('execId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permId', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('acctNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('avgPrice', sa.Float(), nullable=False),
    sa.Column('cumQty', sa.Float(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('realizedPNL', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('execId')
    )
    op.create_index(op.f('ix_execution_execId'), 'execution', ['execId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_execId'), table_name='execution')
    op.drop_table('execution')
    # ### end Alembic commands ###