"""Add dividend accounts table

Revision ID: 84ee53f97357
Revises: 710cafd9a8c6
Create Date: 2026-01-31 19:49:34.879493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '84ee53f97357'
down_revision = '710cafd9a8c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_accounts',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dividend_accounts')
    # ### end Alembic commands ###