"""add linked_id to dividend_accounts

Revision ID: 93b8104cc90e
Revises: 84ee53f97357
Create Date: 2026-01-31 20:23:10.920294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '93b8104cc90e'
down_revision = '84ee53f97357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividend_accounts', sa.Column('linked_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividend_accounts', 'linked_id')
    # ### end Alembic commands ###