"""Add persistent trading models

Revision ID: aaf944172360
Revises: 0bf5a6151a3f
Create Date: 2026-01-31 22:48:28.622497

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aaf944172360'
down_revision = '0bf5a6151a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_account_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('net_liquidation', sa.Float(), nullable=False),
    sa.Column('total_cash', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sec_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('con_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trading_account_config', sa.Column('last_synced', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_account_config', 'last_synced')
    op.drop_table('trading_positions')
    op.drop_table('trading_account_summary')
    # ### end Alembic commands ###