"""add daily_summary table

Revision ID: b2d42d55f559
Revises: fb4bdd3a199b
Create Date: 2025-07-03 14:13:00.349050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b2d42d55f559'
down_revision = 'fb4bdd3a199b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailysummary',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_win', sa.Float(), nullable=False),
    sa.Column('avg_loss', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('note',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('dailysummary')
    # ### end Alembic commands ###