"""add backtest tables

Revision ID: b8f9cb81d6e3
Revises: e4d61af894a7
Create Date: 2025-12-24 16:35:18.966001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8f9cb81d6e3'
down_revision = 'e4d61af894a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtestrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_equity', sa.Float(), nullable=False),
    sa.Column('total_realized_pnl', sa.Float(), nullable=False),
    sa.Column('total_unrealized_pnl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optioncontract',
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('right', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('multiplier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('conid')
    )
    op.create_index(op.f('ix_optioncontract_expiration'), 'optioncontract', ['expiration'], unique=False)
    op.create_index(op.f('ix_optioncontract_symbol'), 'optioncontract', ['symbol'], unique=False)
    op.create_table('backtesttrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtestrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicaloptionbar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('implied_vol', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['conid'], ['optioncontract.conid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicaloptionbar_conid'), 'historicaloptionbar', ['conid'], unique=False)
    op.create_index(op.f('ix_historicaloptionbar_date'), 'historicaloptionbar', ['date'], unique=False)
    op.alter_column('matchedtrade', 'open_transaction_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('matchedtrade', 'close_transaction_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('trade', 'dateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'dateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('matchedtrade', 'close_transaction_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('matchedtrade', 'open_transaction_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_historicaloptionbar_date'), table_name='historicaloptionbar')
    op.drop_index(op.f('ix_historicaloptionbar_conid'), table_name='historicaloptionbar')
    op.drop_table('historicaloptionbar')
    op.drop_table('backtesttrade')
    op.drop_index(op.f('ix_optioncontract_symbol'), table_name='optioncontract')
    op.drop_index(op.f('ix_optioncontract_expiration'), table_name='optioncontract')
    op.drop_table('optioncontract')
    op.drop_table('backtestrun')
    # ### end Alembic commands ###