"""Add dividend cache

Revision ID: cb9ab42f6156
Revises: 93b8104cc90e
Create Date: 2026-01-31 21:17:09.327816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cb9ab42f6156'
down_revision = '93b8104cc90e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_ticker_data',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=False),
    sa.Column('dividend_rate', sa.Float(), nullable=False),
    sa.Column('dgr_3y', sa.Float(), nullable=False),
    sa.Column('dgr_5y', sa.Float(), nullable=False),
    sa.Column('previous_close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dividend_ticker_data')
    # ### end Alembic commands ###