"""add matched_trade table

Revision ID: e4d61af894a7
Revises: c8ce438e9699
Create Date: 2025-07-03 20:29:30.551807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e4d61af894a7'
down_revision = 'c8ce438e9699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchedtrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.Column('close_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchedtrade')
    # ### end Alembic commands ###