-- Migration: 20260504134746_add_options_income_phase1_tables
-- Source: pulled from production (remote-only, issue #335)

do $$ begin create type public.options_sync_source as enum ('ibkr_flex', 'ib_gateway', 'snaptrade'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_sync_status as enum ('pending', 'running', 'succeeded', 'failed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.option_right as enum ('call', 'put'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_strategy_kind as enum ('csp', 'vertical_spread', 'roll_chain', 'ungrouped'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_strategy_status as enum ('open', 'closed', 'expired', 'assigned', 'mixed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_trade_event_type as enum ('open', 'close', 'expire', 'assign', 'exercise', 'cash_settle', 'adjustment'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_trade_side as enum ('buy', 'sell'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_cash_event_category as enum ('option_related', 'commission_fee', 'tax_withholding', 'interest', 'dividend', 'transfer', 'other'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_roll_classification as enum ('positive', 'negative', 'neutral'); exception when duplicate_object then null; end $$;
do $$ begin create type public.options_roll_detection_status as enum ('detected', 'confirmed', 'rejected', 'manual'); exception when duplicate_object then null; end $$;

create table if not exists public.options_flex_sync_state (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, query_name text not null, source public.options_sync_source not null default 'ibkr_flex', status public.options_sync_status not null default 'pending', last_sync_at timestamptz, last_from_date date, last_through_date date, rows_seen integer not null default 0, rows_inserted integer not null default 0, rows_updated integer not null default 0, row_counts jsonb not null default '{}'::jsonb, error text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_flex_sync_state_account_query_key unique (household_id, account_id, query_name, source));
create table if not exists public.options_legs (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, source_conid bigint, underlying_symbol text not null, option_symbol text, expiry date not null, strike numeric(18,6) not null, "right" public.option_right not null, multiplier numeric(18,6) not null default 100, currency text not null default 'USD', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_legs_household_account_conid_key unique nulls not distinct (household_id, account_id, source_conid), constraint options_legs_natural_key unique (household_id, account_id, underlying_symbol, expiry, strike, "right", multiplier, currency));
create table if not exists public.options_strategy_groups (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, underlying_symbol text not null, kind public.options_strategy_kind not null default 'ungrouped', status public.options_strategy_status not null default 'open', opened_at timestamptz not null, closed_at timestamptz, parent_group_id uuid references public.options_strategy_groups(id) on delete set null, net_cash_flow numeric(18,6) not null default 0, realized_pnl numeric(18,6) not null default 0, capital_at_risk numeric(18,6), notes text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.options_trades (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, strategy_group_id uuid references public.options_strategy_groups(id) on delete set null, leg_id uuid not null references public.options_legs(id) on delete restrict, source public.options_sync_source not null, source_trade_id text, source_transaction_id text, source_exec_id text, event_type public.options_trade_event_type not null, side public.options_trade_side not null, trade_time timestamptz not null, trade_date date not null, quantity numeric(18,6) not null, price numeric(18,6) not null, gross_amount numeric(18,6) not null, commission numeric(18,6) not null default 0, fees numeric(18,6) not null default 0, net_cash_flow numeric(18,6) not null, realized_pnl numeric(18,6) not null default 0, matched_open_trade_id uuid references public.options_trades(id) on delete set null, fifo_lot_id uuid, currency text not null default 'USD', raw_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_trades_source_trade_key unique (source, source_trade_id));
create table if not exists public.options_cash_events (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, source public.options_sync_source not null, source_transaction_id text not null, event_date date not null, event_time timestamptz, event_category public.options_cash_event_category not null, description text, amount numeric(18,6) not null, currency text not null default 'USD', related_trade_id uuid references public.options_trades(id) on delete set null, related_strategy_group_id uuid references public.options_strategy_groups(id) on delete set null, raw_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_cash_events_source_transaction_key unique (source, source_transaction_id));
create table if not exists public.options_positions (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, as_of_date date not null, strategy_group_id uuid references public.options_strategy_groups(id) on delete set null, leg_id uuid not null references public.options_legs(id) on delete restrict, opened_at timestamptz not null, quantity_open numeric(18,6) not null, average_open_price numeric(18,6) not null, open_cash_flow numeric(18,6) not null, capital_at_risk numeric(18,6), ib_margin_requirement numeric(18,6), last_broker_sync_at timestamptz, raw_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_positions_snapshot_key unique (household_id, account_id, as_of_date, leg_id));
create table if not exists public.options_roll_events (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, account_id text not null, strategy_group_id uuid not null references public.options_strategy_groups(id) on delete cascade, closed_trade_id uuid not null references public.options_trades(id) on delete cascade, opened_trade_id uuid not null references public.options_trades(id) on delete cascade, detected_at timestamptz not null default now(), detection_status public.options_roll_detection_status not null default 'detected', classification public.options_roll_classification not null, closed_leg_realized_pnl numeric(18,6) not null, incremental_cash_flow numeric(18,6) not null, old_expiry date, new_expiry date, old_strike numeric(18,6), new_strike numeric(18,6), heuristic_version text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint options_roll_events_trade_pair_key unique (household_id, closed_trade_id, opened_trade_id));
create table if not exists public.options_dashboard_monthly (household_id uuid not null references public.households(id) on delete cascade, account_id text not null, period_start date not null, period_end date not null, cash_flow_total numeric(18,6) not null default 0, realized_pnl_total numeric(18,6) not null default 0, cash_flow_cumulative numeric(18,6) not null default 0, realized_pnl_cumulative numeric(18,6) not null default 0, variance_gap numeric(18,6) not null default 0, variance_gap_cumulative numeric(18,6) not null default 0, trade_count integer not null default 0, roll_efficiency_positive_count integer, roll_efficiency_negative_count integer, roll_efficiency_neutral_count integer, roll_efficiency_score numeric(18,6), capital_at_risk_avg numeric(18,6), capital_at_risk_return numeric(18,6), last_computed_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (household_id, account_id, period_start));

create index if not exists options_flex_sync_state_account_idx on public.options_flex_sync_state (account_id, last_sync_at desc);
create index if not exists options_legs_account_underlying_idx on public.options_legs (household_id, account_id, underlying_symbol);
create index if not exists options_strategy_groups_account_status_idx on public.options_strategy_groups (household_id, account_id, status);
create index if not exists options_trades_account_trade_date_idx on public.options_trades (household_id, account_id, trade_date);
create index if not exists options_trades_leg_id_idx on public.options_trades (leg_id);
create index if not exists options_cash_events_account_event_date_idx on public.options_cash_events (household_id, account_id, event_date);
create index if not exists options_positions_account_as_of_idx on public.options_positions (household_id, account_id, as_of_date desc);
create index if not exists options_roll_events_account_detected_idx on public.options_roll_events (household_id, account_id, detected_at desc);
create index if not exists options_dashboard_monthly_account_period_idx on public.options_dashboard_monthly (household_id, account_id, period_start desc);
