-- Migration: 20260504134817_add_options_income_phase1_policies
-- Source: pulled from production (remote-only, issue #335)

drop trigger if exists trg_options_flex_sync_state_updated_at on public.options_flex_sync_state; create trigger trg_options_flex_sync_state_updated_at before update on public.options_flex_sync_state for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_legs_updated_at on public.options_legs; create trigger trg_options_legs_updated_at before update on public.options_legs for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_strategy_groups_updated_at on public.options_strategy_groups; create trigger trg_options_strategy_groups_updated_at before update on public.options_strategy_groups for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_trades_updated_at on public.options_trades; create trigger trg_options_trades_updated_at before update on public.options_trades for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_cash_events_updated_at on public.options_cash_events; create trigger trg_options_cash_events_updated_at before update on public.options_cash_events for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_positions_updated_at on public.options_positions; create trigger trg_options_positions_updated_at before update on public.options_positions for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_roll_events_updated_at on public.options_roll_events; create trigger trg_options_roll_events_updated_at before update on public.options_roll_events for each row execute function public.tg_update_timestamp();
drop trigger if exists trg_options_dashboard_monthly_updated_at on public.options_dashboard_monthly; create trigger trg_options_dashboard_monthly_updated_at before update on public.options_dashboard_monthly for each row execute function public.tg_update_timestamp();

alter table public.options_flex_sync_state enable row level security; alter table public.options_legs enable row level security; alter table public.options_strategy_groups enable row level security; alter table public.options_trades enable row level security; alter table public.options_cash_events enable row level security; alter table public.options_positions enable row level security; alter table public.options_roll_events enable row level security; alter table public.options_dashboard_monthly enable row level security;

revoke all on table public.options_flex_sync_state, public.options_legs, public.options_strategy_groups, public.options_trades, public.options_cash_events, public.options_positions, public.options_roll_events, public.options_dashboard_monthly from anon;
revoke all on table public.options_flex_sync_state, public.options_legs, public.options_strategy_groups, public.options_trades, public.options_cash_events, public.options_positions, public.options_roll_events, public.options_dashboard_monthly from authenticated;
grant select, insert, update, delete on table public.options_flex_sync_state, public.options_legs, public.options_strategy_groups, public.options_trades, public.options_cash_events, public.options_positions, public.options_roll_events, public.options_dashboard_monthly to authenticated;
grant select, insert, update, delete on table public.options_flex_sync_state, public.options_legs, public.options_strategy_groups, public.options_trades, public.options_cash_events, public.options_positions, public.options_roll_events, public.options_dashboard_monthly to service_role;

drop policy if exists options_flex_sync_state_select on public.options_flex_sync_state; create policy options_flex_sync_state_select on public.options_flex_sync_state for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_flex_sync_state_insert on public.options_flex_sync_state; create policy options_flex_sync_state_insert on public.options_flex_sync_state for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_flex_sync_state_update on public.options_flex_sync_state; create policy options_flex_sync_state_update on public.options_flex_sync_state for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_flex_sync_state_delete on public.options_flex_sync_state; create policy options_flex_sync_state_delete on public.options_flex_sync_state for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_legs_select on public.options_legs; create policy options_legs_select on public.options_legs for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_legs_insert on public.options_legs; create policy options_legs_insert on public.options_legs for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_legs_update on public.options_legs; create policy options_legs_update on public.options_legs for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_legs_delete on public.options_legs; create policy options_legs_delete on public.options_legs for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_strategy_groups_select on public.options_strategy_groups; create policy options_strategy_groups_select on public.options_strategy_groups for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_strategy_groups_insert on public.options_strategy_groups; create policy options_strategy_groups_insert on public.options_strategy_groups for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_strategy_groups_update on public.options_strategy_groups; create policy options_strategy_groups_update on public.options_strategy_groups for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_strategy_groups_delete on public.options_strategy_groups; create policy options_strategy_groups_delete on public.options_strategy_groups for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_trades_select on public.options_trades; create policy options_trades_select on public.options_trades for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_trades_insert on public.options_trades; create policy options_trades_insert on public.options_trades for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_trades_update on public.options_trades; create policy options_trades_update on public.options_trades for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_trades_delete on public.options_trades; create policy options_trades_delete on public.options_trades for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_cash_events_select on public.options_cash_events; create policy options_cash_events_select on public.options_cash_events for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_cash_events_insert on public.options_cash_events; create policy options_cash_events_insert on public.options_cash_events for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_cash_events_update on public.options_cash_events; create policy options_cash_events_update on public.options_cash_events for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_cash_events_delete on public.options_cash_events; create policy options_cash_events_delete on public.options_cash_events for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_positions_select on public.options_positions; create policy options_positions_select on public.options_positions for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_positions_insert on public.options_positions; create policy options_positions_insert on public.options_positions for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_positions_update on public.options_positions; create policy options_positions_update on public.options_positions for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_positions_delete on public.options_positions; create policy options_positions_delete on public.options_positions for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_roll_events_select on public.options_roll_events; create policy options_roll_events_select on public.options_roll_events for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_roll_events_insert on public.options_roll_events; create policy options_roll_events_insert on public.options_roll_events for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_roll_events_update on public.options_roll_events; create policy options_roll_events_update on public.options_roll_events for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_roll_events_delete on public.options_roll_events; create policy options_roll_events_delete on public.options_roll_events for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

drop policy if exists options_dashboard_monthly_select on public.options_dashboard_monthly; create policy options_dashboard_monthly_select on public.options_dashboard_monthly for select to authenticated using (household_id is not null and public.is_household_member(household_id));
drop policy if exists options_dashboard_monthly_insert on public.options_dashboard_monthly; create policy options_dashboard_monthly_insert on public.options_dashboard_monthly for insert to authenticated with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_dashboard_monthly_update on public.options_dashboard_monthly; create policy options_dashboard_monthly_update on public.options_dashboard_monthly for update to authenticated using (household_id is not null and public.is_household_writer(household_id)) with check (household_id is not null and public.is_household_writer(household_id));
drop policy if exists options_dashboard_monthly_delete on public.options_dashboard_monthly; create policy options_dashboard_monthly_delete on public.options_dashboard_monthly for delete to authenticated using (household_id is not null and public.is_household_writer(household_id));

do $$ begin alter publication supabase_realtime add table public.options_flex_sync_state; exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.options_strategy_groups; exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.options_positions; exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.options_roll_events; exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.options_dashboard_monthly; exception when duplicate_object then null; when undefined_object then null; end $$;
