-- Migration: 20260506200000_household_invites_schema
-- Author: Hockney (Backend Dev)
-- Purpose: Create household_invites table, RLS policies, helper functions, and
--          optional FK back-fill for household_audit_log.target_invite_id.
-- Issues: #74 (TJ-021) — pre-req; Fenster builds invite UI/Server Actions on top.
--         Cross-links #77 (audit trail): invite_created / invite_accepted /
--         invite_revoked events emitted by the Server Actions via audit.ts.
--
-- DESIGN NOTES:
--   - Status lifecycle: pending → accepted | revoked | expired (status-column FSM).
--     Rows are NEVER deleted — soft lifecycle only. This preserves audit history
--     and lets the audit trail FK (added below) remain meaningful.
--   - role column uses the existing public.household_role enum ('owner','member','viewer')
--     so the granted role on accept_invite() feeds directly into household_members.role.
--   - invited_by_user_id is nullable (ON DELETE SET NULL) matching the pattern used
--     by household_members.invited_by. The application always sets it at INSERT time;
--     it becomes NULL only if the sender's auth.users row is hard-deleted.
--   - invite_token: 64-char hex string, 256 bits of entropy, always URL-safe.
--     Generated by gen_invite_token() using two gen_random_uuid() calls
--     (built-in Postgres 13+, no pgcrypto extension required).
--   - expires_at: enforced by accept_invite(); callers should set 7 days from now().
--   - accept_invite(token): SECURITY DEFINER — performs atomic accept + member insert
--     in a single transaction, bypassing RLS for the household_members write (which
--     normally requires the owner role). Returns the invite UUID for the caller to
--     pass to recordInviteAccepted() in the audit helper.
--   - FK from household_audit_log.target_invite_id → household_invites(id):
--     Added here as NOT VALID (existing null rows not re-checked). R11 comment
--     "no FK: invites are short-lived" no longer holds — this migration keeps invite
--     rows indefinitely via status FSM. ON DELETE SET NULL preserves audit entries
--     even if a household cascades.

-- ============================================================
-- Status enum
-- ============================================================
do $$ begin
  create type public.household_invite_status as enum (
    'pending',
    'accepted',
    'revoked',
    'expired'
  );
exception when duplicate_object then null;
end $$;

-- ============================================================
-- household_invites
-- ============================================================
create table if not exists public.household_invites (
  id                    uuid                              primary key default gen_random_uuid(),
  household_id          uuid                              not null references public.households(id) on delete cascade,
  invited_email         text                              not null,
  -- nullable: matches household_members.invited_by pattern; set null if sender is deleted
  invited_by_user_id    uuid                              references auth.users(id) on delete set null,
  -- 64-char hex token (256-bit entropy). Use gen_invite_token() to generate.
  -- MUST NOT be stored in audit metadata; reference by id only.
  invite_token          text                              not null unique,
  role                  public.household_role             not null default 'member',
  status                public.household_invite_status    not null default 'pending',
  expires_at            timestamptz                       not null,
  created_at            timestamptz                       not null default now(),
  updated_at            timestamptz                       not null default now(),
  -- Acceptance fields — set atomically by accept_invite()
  accepted_at           timestamptz,
  accepted_by_user_id   uuid                              references auth.users(id) on delete set null,
  -- Revocation fields — set by the owner via Server Action
  revoked_at            timestamptz,
  revoked_by_user_id    uuid                              references auth.users(id) on delete set null
);

comment on table public.household_invites is
  'Pending, accepted, revoked, and expired invitations to join a household. '
  'Rows are never deleted — status FSM provides the lifecycle. '
  'Raw invite_token MUST NOT appear in audit metadata or logs.';

comment on column public.household_invites.invite_token is
  '256-bit hex token (64 chars). URL-safe. Generated by gen_invite_token(). '
  'Used in invite links. Must be treated as a secret — never log or audit-trail raw.';
comment on column public.household_invites.role is
  'Role granted on acceptance. Must match public.household_role enum values.';
comment on column public.household_invites.status is
  'FSM: pending → accepted | revoked | expired. '
  'accept_invite() transitions pending→accepted atomically.';
comment on column public.household_invites.expires_at is
  'Hard expiry enforced by accept_invite(). Recommended: 7 days from created_at. '
  'Expired rows remain with status=''pending'' until a cleanup job or manual revoke.';
comment on column public.household_invites.accepted_by_user_id is
  'auth.users.id of the user who accepted the invite (may differ from invited_email '
  'if link was forwarded — we record who actually accepted).';

-- ============================================================
-- Indexes
-- ============================================================

-- Composite uniqueness: only one PENDING invite per (household_id, email).
-- Multiple historical invites are allowed (accepted / revoked / expired rows persist).
create unique index if not exists household_invites_unique_pending
  on public.household_invites (household_id, lower(invited_email))
  where status = 'pending';

-- Fast token look-up (accept_invite() hot path)
create index if not exists household_invites_token_lookup
  on public.household_invites (invite_token)
  where status = 'pending';

-- Owner dashboard: list invites for a household, ordered by recency
create index if not exists household_invites_household_status
  on public.household_invites (household_id, status, created_at desc);

-- Invited-user dashboard: "what invites are waiting for me?"
create index if not exists household_invites_email_pending
  on public.household_invites (lower(invited_email))
  where status = 'pending';

-- ============================================================
-- updated_at trigger — matches tg_update_timestamp() convention
-- ============================================================
drop trigger if exists trg_household_invites_updated_at on public.household_invites;
create trigger trg_household_invites_updated_at
  before update on public.household_invites
  for each row execute function public.tg_update_timestamp();

-- ============================================================
-- RLS
-- ============================================================
alter table public.household_invites enable row level security;

-- ---- SELECT ----

-- Household owners can see all invites for households they own
drop policy if exists household_invites_owner_select on public.household_invites;
create policy household_invites_owner_select
  on public.household_invites
  for select
  using (public.is_household_owner(household_id));

-- Invited users can see their own pending invites
-- (matched via email claim in the JWT so the user can view their invite dashboard)
drop policy if exists household_invites_invited_select on public.household_invites;
create policy household_invites_invited_select
  on public.household_invites
  for select
  using (
    status = 'pending'
    and lower(invited_email) = lower(coalesce(
      (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email'),
      ''
    ))
  );

-- ---- INSERT ----

-- Only the household owner may send invites for their household
drop policy if exists household_invites_owner_insert on public.household_invites;
create policy household_invites_owner_insert
  on public.household_invites
  for insert
  with check (public.is_household_owner(household_id));

-- ---- UPDATE ----

-- Only the household owner may UPDATE invites (used to revoke: status → 'revoked').
-- Acceptance is handled exclusively through accept_invite() (SECURITY DEFINER) which
-- bypasses RLS — no separate authenticated-user UPDATE policy needed for acceptance.
drop policy if exists household_invites_owner_update on public.household_invites;
create policy household_invites_owner_update
  on public.household_invites
  for update
  using (public.is_household_owner(household_id));

-- ---- DELETE ----

-- Hard deletes are forbidden for all roles; use status = 'revoked' / 'expired'.
drop policy if exists household_invites_no_hard_delete on public.household_invites;
create policy household_invites_no_hard_delete
  on public.household_invites
  for delete
  using (false);

-- ============================================================
-- Grant / revoke — authenticated role
-- Mirrors audit_trail convention: restrict anon; service_role bypasses RLS.
-- ============================================================
revoke all  on public.household_invites from anon;
-- Authenticated users can SELECT and INSERT (RLS narrows to owner / invited-email).
-- UPDATE restricted to owners via RLS; acceptance goes through security-definer fn.
grant select, insert, update on public.household_invites to authenticated;

-- ============================================================
-- Helper: gen_invite_token()
-- Returns a 256-bit hex token (64 chars). URL-safe, no padding ambiguity.
-- Call from Server Action before INSERT into household_invites.
-- INVOKER security: uses gen_random_uuid() (built-in Postgres 13+, no extension needed).
-- Two UUIDs concatenated = 64 hex chars = 256 bits of entropy.
-- ============================================================
create or replace function public.gen_invite_token()
returns text
language sql
security invoker
set search_path = public, pg_temp
as $$
  select replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
$$;

comment on function public.gen_invite_token() is
  'Generate a 256-bit URL-safe hex token (64 chars) for household invite links. '
  'Must be stored in household_invites.invite_token and included in the invite URL '
  'as a query parameter. Treat as a secret — never log or store in audit metadata.';

revoke execute on function public.gen_invite_token() from public;
grant  execute on function public.gen_invite_token() to authenticated;

-- ============================================================
-- Helper: accept_invite(p_token)
-- Atomically accepts a pending, non-expired invite for the current authenticated user:
--   1. Locks and validates the invite row (pending + not expired).
--   2. Upserts into household_members with the invite's role.
--      ON CONFLICT DO NOTHING — safe if user is somehow already a member.
--   3. Sets status = 'accepted', accepted_at, accepted_by_user_id.
-- Returns the invite UUID — pass to recordInviteAccepted() in audit.ts.
-- SECURITY DEFINER: bypasses RLS for the household_members INSERT (which is
-- normally restricted to owners). Caller must be authenticated (auth.uid() checked).
-- ============================================================
create or replace function public.accept_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_invite  public.household_invites%rowtype;
  v_uid     uuid;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'Not authenticated — auth.uid() is null'
      using errcode = 'P0001';
  end if;

  -- Lock the invite row to prevent double-accept race conditions
  select *
  into   v_invite
  from   public.household_invites
  where  invite_token = p_token
    and  status       = 'pending'
    and  expires_at   > now()
  for update;

  if not found then
    raise exception 'Invite not found, already used, revoked, or expired'
      using errcode = 'P0002';
  end if;

  -- Upsert into household_members; idempotent if user is already a member
  insert into public.household_members (household_id, user_id, role, invited_by)
  values (
    v_invite.household_id,
    v_uid,
    v_invite.role,
    v_invite.invited_by_user_id
  )
  on conflict (household_id, user_id) do nothing;

  -- Mark invite accepted
  update public.household_invites
  set
    status              = 'accepted',
    accepted_at         = now(),
    accepted_by_user_id = v_uid,
    updated_at          = now()
  where id = v_invite.id;

  return v_invite.id;
end;
$$;

comment on function public.accept_invite(text) is
  'Atomically accept a pending, non-expired invite by token. '
  'Inserts the caller into household_members with the invite''s role, then marks '
  'the invite as accepted. Returns the invite UUID for the audit helper. '
  'Raises P0001 if unauthenticated; P0002 if token is invalid / expired / used. '
  'Caller MUST emit recordInviteAccepted(householdId, newMemberId, inviteId) after '
  'this function returns successfully.';

-- Authenticated users may call this function (RLS-level auth check is inside)
revoke execute on function public.accept_invite(text) from public;
grant  execute on function public.accept_invite(text) to authenticated;

-- ============================================================
-- Optional: add FK from household_audit_log.target_invite_id
-- → household_invites(id) ON DELETE SET NULL
--
-- R11 comment "no FK: invites are short-lived" is superseded by this migration:
-- invite rows are kept indefinitely (status FSM). NOT VALID skips checking
-- pre-existing NULL rows in the audit log; only new inserts are validated.
-- ============================================================
do $$ begin
  if not exists (
    select 1
    from   information_schema.referential_constraints
    where  constraint_name   = 'household_audit_log_target_invite_fk'
      and  constraint_schema = 'public'
  ) then
    alter table public.household_audit_log
      add constraint household_audit_log_target_invite_fk
      foreign key (target_invite_id)
      references public.household_invites(id)
      on delete set null
      not valid;

    comment on constraint household_audit_log_target_invite_fk
      on public.household_audit_log is
      'Soft FK added in R12 migration (household_invites_schema). '
      'NOT VALID — existing NULL rows are not re-checked. '
      'ON DELETE SET NULL preserves audit rows if an invite is ever hard-deleted '
      '(e.g., via household CASCADE). Supersedes the R11 "no FK: short-lived" comment.';
  end if;
end $$;

-- end of migration
